#!/usr/bin/env bash

# Title: kr40's CTF Automator
# Description: This is a simple script to automate the process of making directories and files for CTF
# Author: Kartik Rao <kr40.git@gmail.com>
# Date: 2022-08-09
# Version: 1.0.0

# Usage: bannerSimple "my title" "*"
function bannerSimple() {
    local msg="${2} ${1} ${2}"
    local edge
    edge=${msg//?/$2}
    echo "${edge}"
    echo "$(tput bold)${msg}$(tput sgr0)"
    echo "${edge}"
    echo
}

bannerSimple "CTF Automator" "*"

printf 'This is a simple script to automate the process of making directories and files for CTF\n'
sleep 1
read -p "Enter the CTF VPN to start? (htb-labs, htb-startingpoint, htb-academy, thm):" vpn

echo "You chose $vpn"

echo "Starting $vpn vpn via OpenVPN"

if [[ $vpn == "htb-labs" ]]; then
    gnome-terminal -- sudo openvpn ~/Desktop/ctf/vpn/htb-labs.ovpn
elif [[ $vpn == "htb-startingpoint" ]]; then
    gnome-terminal -- sudo openvpn ~/Desktop/ctf/vpn/htb-startingpoint.ovpn
elif [[ $vpn == "htb-academy" ]]; then
    gnome-terminal -- sudo openvpn ~/Desktop/ctf/vpn/htb-academy.ovpn
elif [[ $vpn == "thm" ]]; then
    gnome-terminal -- sudo openvpn ~/Desktop/ctf/vpn/thm-labs.ovpn
else
    echo "Please enter the correct name"
fi

if [[ $? == 0 ]]; then
    echo "$vpn Started"
fi

read -p "Enter the CTF Box Name:" boxname

if [[ $vpn == "htb-labs" ]]; then
    cd Desktop/ctf/htb/htb_labs || exit
    mkdir "$boxname"
    cd "$boxname" || exit
    mkdir nmap
    cd Desktop/ctf/htb/htb_labs/"$boxname" || exit
elif [[ $vpn == "htb-startingpoint" ]]; then
    read -p "Enter the tier (0,1,2):" tier
    if [[ $tier == 0 ]]; then
        cd Desktop/ctf/htb/htb_startingpoint/tier_0/ || exit
        mkdir "$boxname"
        cd "$boxname" || exit
        mkdir "nmap"
        cp ~/Desktop/ctf/htb/htb_startingpoint/tier_0/template.md ~/Desktop/ctf/htb/htb_startingpoint/tier_0/"$boxname"/README.md || exit
        cd ~/Desktop/ctf/htb/htb_startingpoint/tier_0/"$boxname" || exit
    elif [[ $tier == 1 ]]; then
        cd Desktop/ctf/htb/htb_startingpoint/tier_1/ || exit
        mkdir "$boxname"
        cd "$boxname" || exit
        mkdir "nmap"
        cp ~/Desktop/ctf/htb/htb_startingpoint/tier_1/template.md ~/Desktop/ctf/htb/htb_startingpoint/tier_1/"$boxname"/README.md || exit
        cd ~/Desktop/ctf/htb/htb_startingpoint/tier_1/"$boxname" || exit
    elif [[ $tier == 0 ]]; then
        cd Desktop/ctf/htb/htb_startingpoint/tier_2/ || exit
        mkdir "$boxname"
        cd "$boxname" || exit
        mkdir "nmap"
        cp ~/Desktop/ctf/htb/htb_startingpoint/tier_2/template.md ~/Desktop/ctf/htb/htb_startingpoint/tier_2/"$boxname"/README.md || exit
        cd ~/Desktop/ctf/htb/htb_startingpoint/tier_2/"$boxname" || exit
    fi
elif [[ $vpn == "htb-academy" ]]; then
    cd Desktop/ctf/htb/htb_academy || exit
    mkdir "$boxname"
    cd "$boxname" || exit
    mkdir nmap
    cd Desktop/ctf/htb/htb_academy/"$boxname" || exit
elif [[ $vpn == "thm" ]]; then
    cd Desktop/ctf/thm || exit
    mkdir "$boxname"
    cd "$boxname" || exit
    mkdir nmap
    cd Desktop/ctf/thm/"$boxname" || exit
fi

echo "Added Necessary Files and Folders for your CTF Box!! Happy Hacking"
exit 0
